<?php

  $url = "https://api.us-south.speech-to-text.watson.cloud.ibm.com/instances/e167c678-2188-4665-b306-96637b8cd51c";
  $apikey = "z7YeOpDC16-zY09vrNgk49DhADD-YZpuLQrqtf8mVA6l";
  //$path_to_file = "../audio/1.mp3";
  //$path_to_file = realpath("../audio/1.mp3");
  //$path_to_file = "https://watson-developer-cloud.github.io/doc-tutorial-downloads/speech-to-text/audio-file.flac";
  $path_to_file = "http://zeddevelopers.com/testing/1.mp3";

  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, "$url/v1/recognize?timestamps=true&max_alternatives=3");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  $post = array(
      'file' => '@' .$path_to_file
  );
  curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
  curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . $apikey);

  $headers = array();
  $headers[] = 'Content-Type: audio/mp3';
  //$headers[] = 'Transfer-Encoding: chunked';

  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);
  if (curl_errno($ch)) {
      echo 'Error:' . curl_error($ch);
  }
  curl_close($ch);

  echo $result;
?>
